[package]
name = "floating_pills"
version = "0.1.0"
edition = "2021"
workspace = "NO_PATH"

[lib]
crate-type = ["cdylib"]
path = "src/project.rs"

[dependencies]
pill_engine = { path = "../../engine/pill_engine", features = ["project"] }

rand = "0.8.4"
glam = { version = "0.30.8", features = ["serde"] }

[features]
benchmark = []

default = ["benchmark"]

[profile.release]
lto = "thin"
