[workspace]
resolver = "2"
members = [
    "crates/pill_core", 
    "crates/pill_engine", 
    "crates/pill_renderer", 
    "crates/pill_standalone",
    "crates/pill_game", # This is a symlink to the actual game project, set automatically by Pill Launcher
    "crates/pill_launcher",
]

exclude = [
     
]