[workspace]
resolver = "2"
members = [
    "crates/pill_core", 
    "crates/pill_engine", 
    "crates/pill_renderer", 
    "crates/pill_standalone"
    ]

exclude = [
    "crates/pill_launcher",
    ]