[workspace]
resolver = "2"
members = [
    "pill_core",
    "pill_engine",
    "pill_renderer",
    "pill_standalone",
    "pill_headless",
    "pill_net",
    "/home/jduchniewicz/Projects/Sticky-Piston-Studios/Pill-Engine/examples/Net-Minimal", ### Game project crate (This will be changed by Pill Launcher on build to allow proper compilation of game project)
]

exclude = [
    "pill_launcher",
]
