[package]
name = "pill_engine"
version = "0.1.0"
authors = [
    # Extend this list when submiting PR
    "Mateusz Szymoński <mateusz.szymonski@gmail.com>"
    ]
edition = "2018"
resolver = "2"

[dependencies]
pill_core = {path = "../pill_core"}

cgmath = "0.18"
winit = "0.25"
cfg-if = "1.0.0"

[features]
game = []
internal = []