[package]
name = "pill_launcher"
version = "0.1.0"
edition = "2018"

[dependencies]
clap = { version = "3.0.0", features = ["derive"] }
fs_extra = "1.2.0"
rust-ini = "0.17.0"
anyhow = "1.0"
walkdir = "2.0"