[package]
name = "pill_launcher"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "PillLauncher"
path = "src/main.rs"

[dependencies]
clap = "2.34.0"
fs_extra = "1.2.0"
anyhow = "1.0"
path-absolutize = "3.0.11"
config = "0.11"
