[package]
name = "pill_game"
version = "0.1.0"
edition = "2018"
build = "build.rs"
resolver = "2"

[dependencies]
pill_engine = {path = "../../crates/pill_engine", features = ["game"]}
cgmath = "0.18"