[package]
name = "pill_game"
version = "0.1.0"
edition = "2021"

[dependencies]
pill_engine = {path = "/home/jduchniewicz/Projects/Sticky-Piston-Studios/Pill-Engine/crates/pill_engine", features = ["game"]}

rand = "0.8.4"
cgmath = "0.18.0"
