[package]
name = "pill_game"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
log    = "0.4"

# Build the engine as a client (rendering+audio+ui+net+internal)
pill_engine = { path = "/home/jduchniewicz/Projects/Sticky-Piston-Studios/Pill-Engine/crates/pill_engine", features = ["rendering", "audio", "ui", "internal", "net", "game"] }

[features]
default = ["net"]

# Local feature that mirrors the engine's `net` in case you guard any code with #[cfg(feature="net")]
net = ["pill_engine/net"]

