# GAME
TITLE=PBR Helmet

# WINDOW
WINDOW_TITLE=Pill Engine - PBR Helmet
WINDOW_WIDTH=1920
WINDOW_HEIGHT=1080
WINDOW_FULLSCREEN=false

# ENGINE GENERAL
MAX_ENTITYS=100
MAX_CAMERAS=1
MAX_CONCURRENT_2D_SOUNDS=0
MAX_CONCURRENT_3D_SOUNDS=0

# ENGINE RESOURCES
MAX_TEXTURES=10
MAX_MATERIALS=10
MAX_MESHS=10
MAX_SOUNDS=0

# OTHER
LOG_LEVEL=Info
PANIC_ON_GAME_ERRORS=true
